import SwiftUI

struct CoachView:View{
    @EnvironmentObject var app:AppModel
    @State private var section=0
    @State private var showTest=false
    @State private var testMinutes=5
    var body:some View{ScrollView{VStack(alignment:.leading,spacing:13){Text("FITNESS & COACH").font(.title.weight(.black));Picker("Fitness section",selection:$section){Text("VO₂ & TESTS").tag(0);Text("SHORT RANGE").tag(1)}.pickerStyle(.segmented)
        if section==0{GlassCard{VStack(alignment:.leading,spacing:12){Text("CYCLING VO₂ MAX").font(.caption.weight(.black)).foregroundStyle(IRTheme.cyan);HStack(alignment:.lastTextBaseline){Text(app.fitness.vo2>0 ? String(format:"%0.1f",app.fitness.vo2):"--").font(.system(size:66,weight:.black,design:.rounded));Text("ml/kg/min").foregroundStyle(IRTheme.muted)};Text(app.fitness.summary).font(.callout).foregroundStyle(IRTheme.muted).fixedSize(horizontal:false,vertical:true);Divider().overlay(IRTheme.line);HStack{Button("5-MINUTE TEST"){testMinutes=5;showTest=true}.buttonStyle(.borderedProminent);Button("10-MINUTE TEST"){testMinutes=10;showTest=true}.buttonStyle(.bordered)}}}}
        else{GlassCard{VStack(alignment:.leading,spacing:11){Text("SHORT-RANGE PERFORMANCE").font(.caption.weight(.black)).foregroundStyle(IRTheme.lime);Text(app.fitness.qualifying ? String(format:"VO₂ %0.1f",app.fitness.shortRangeVO2):"NO QUALIFYING EFFORT").font(.title.weight(.black));Text(String(format:"MAX 5-SECOND OUTPUT  %0.0f W",app.fitness.maxSprint)).font(.headline).foregroundStyle(IRTheme.orange);Text("Requires at least 75 seconds, 0.30 mile, 70% HR coverage, ≥65% HR reserve and no downhill bias. Weak evidence cannot alter headline VO₂ or FTP.").font(.caption).foregroundStyle(IRTheme.muted)}}}
        GlassCard{VStack(alignment:.leading,spacing:9){Text("AURORA • OFFLINE RIDE ENGINEER").font(.caption.weight(.black)).foregroundStyle(IRTheme.cyan);Text(coachText()).font(.body);Text("FTP  \(Int(app.fitness.ftp)) W").font(.headline).foregroundStyle(IRTheme.lime)}}
    }.padding(16)}.background(IRTheme.background).foregroundStyle(.white).alert("Start \(testMinutes)-minute VO₂ field test?",isPresented:$showTest){Button("Start test"){app.start(.soloTimeTrial)};Button("Cancel",role:.cancel){}}message:{Text("Use a safe, flat, uninterrupted route. Stop for chest pain, dizziness or unusual breathlessness. This is a fitness estimate, not a clinical test.")}}
    private func coachText()->String{if app.rides.isEmpty{return "Record or import a ride and I’ll evaluate VO₂, FTP, pacing, sustained speed, sprint output and recovery evidence."};if app.fitness.qualifying{return "Your latest high-speed segment cleared the physiological evidence gate. I kept its influence conservative and capped how far one ride can move your main VO₂."};return "Your ride is saved, but its fastest segment did not clear every short-range gate. Build a longer flat effort with stable heart-rate and cadence data."}
}
