import SwiftUI
import MapKit

struct HomeView: View {
    @EnvironmentObject var app:AppModel
    @EnvironmentObject var bluetooth:BluetoothSensorManager
    @State private var showStart=false,showSensors=false
    var body:some View{ScrollView{VStack(alignment:.leading,spacing:14){
        HStack{Image("app_logo").resizable().scaledToFill().frame(width:44,height:44).clipShape(RoundedRectangle(cornerRadius:11));VStack(alignment:.leading,spacing:2){Text("INFINITERIDE").font(.headline.weight(.black)).tracking(1);Text("ULTIMATE • iOS").font(.caption.weight(.bold)).foregroundStyle(IRTheme.cyan)};Spacer();Button{app.tab = .profile}{Image(systemName:"gearshape.fill").font(.title2)}}
        VStack(alignment:.leading,spacing:3){Text("Good \(period()), \(app.profile.name)").font(.system(size:31,weight:.bold,design:.rounded));Text("Ride further. A stronger you is out there.").foregroundStyle(IRTheme.muted)}
        Button{showSensors=true}{GlassCard{HStack(spacing:13){Image(systemName:"applewatch").font(.system(size:35)).foregroundStyle(IRTheme.cyan);VStack(alignment:.leading){Text(bluetooth.devices.first(where:\.connected)?.name ?? "Sensors & Watch").font(.headline);Text(app.connectedSensors>0 ? "\(app.connectedSensors) connected • LIVE":"Tap to connect multiple devices").font(.caption).foregroundStyle(app.connectedSensors>0 ? IRTheme.lime:IRTheme.muted)};Spacer();HeartMetric(heartRate:app.heartRate).frame(width:116);Image(systemName:"chevron.right")}}}.buttonStyle(.plain)
        Button{showStart=true}{HStack{Spacer();Image(systemName:"figure.outdoor.cycle").font(.title2);Text("START RIDE").font(.title2.weight(.black));Spacer();Image(systemName:"chevron.right").font(.title2)}}.foregroundStyle(.black).padding(.vertical,15).padding(.horizontal,19).background(IRTheme.lime).clipShape(Capsule())
        GlassCard{VStack(alignment:.leading,spacing:9){HStack{VStack(alignment:.leading){Text("FEATURED ROUTE").font(.caption.weight(.bold)).foregroundStyle(IRTheme.cyan);Text(app.selectedRouteName.isEmpty ? "Local Road Ahead":app.selectedRouteName).font(.title3.weight(.bold))};Spacer();Text("View map ›").font(.caption)};RouteMap(route:app.selectedRoute,compact:true).frame(height:165).clipShape(RoundedRectangle(cornerRadius:13));Text(app.selectedRoute.isEmpty ? "Import a GPX, TCX or FIT course from Data":"\(app.selectedRoute.count) course points ready").font(.caption).foregroundStyle(IRTheme.muted)}}
        if let ride=app.rides.first{Button{app.analyze(ride);app.tab = .data}{GlassCard{VStack(alignment:.leading,spacing:9){HStack{Text("LAST RIDE").font(.caption.weight(.bold)).foregroundStyle(IRTheme.muted);Spacer();Text(ride.startedAt.formatted(date:.abbreviated,time:.omitted)).font(.caption)};HStack{summary(String(format:"%.1f",ride.distanceMeters/(app.profile.metric ? 1000:1609.344)),app.profile.metric ? "km":"mi");Divider();summary(String(format:"%.1f",ride.averageSpeedMps*(app.profile.metric ? 3.6:2.236936)),app.profile.metric ? "km/h":"mph");Divider();summary(app.fitness.vo2>0 ? String(format:"%.1f",app.fitness.vo2):"--","VO₂")};Text(app.fitness.summary).font(.caption).foregroundStyle(IRTheme.muted).lineLimit(2)}}}.buttonStyle(.plain)}
        HStack(spacing:10){quick("Training","chart.bar.fill",IRTheme.cyan){app.tab = .coach};quick("Routes","map.fill",IRTheme.lime){app.tab = .data};quick("Race","flag.checkered",IRTheme.orange){showStart=true}}
        Text(app.message).font(.caption.weight(.bold)).foregroundStyle(IRTheme.cyan).frame(maxWidth:.infinity,alignment:.center)
    }.padding(18)}.sheet(isPresented:$showStart){StartRideSheet()}.sheet(isPresented:$showSensors){SensorSheet()}}
    private func summary(_ value:String,_ label:String)->some View{VStack(alignment:.leading){Text(value).font(.title3.weight(.bold));Text(label).font(.caption2).foregroundStyle(IRTheme.muted)}.frame(maxWidth:.infinity,alignment:.leading)}
    private func quick(_ title:String,_ symbol:String,_ color:Color,action:@escaping()->Void)->some View{Button(action:action){VStack(alignment:.leading,spacing:12){Image(systemName:symbol).font(.title).foregroundStyle(color);Text(title).font(.headline);Image(systemName:"chevron.right").frame(maxWidth:.infinity,alignment:.trailing)}.padding(14).frame(maxWidth:.infinity,alignment:.leading).background(IRTheme.panel).clipShape(RoundedRectangle(cornerRadius:16))}.buttonStyle(.plain)}
    private func period()->String{let h=Calendar.current.component(.hour,from:Date());return h<12 ? "morning":h<17 ? "afternoon":h<21 ? "evening":"night"}
}

struct StartRideSheet:View{
    @EnvironmentObject var app:AppModel;@Environment(\.dismiss) var dismiss
    var body:some View{NavigationStack{ScrollView{VStack(spacing:11){ForEach(RideKind.allCases){kind in Button{dismiss();app.start(kind)}label:{HStack(spacing:15){Image(systemName:kind.symbol).font(.title2).foregroundStyle(kind.isRace ? IRTheme.orange:IRTheme.cyan).frame(width:38);VStack(alignment:.leading){Text(kind.title).font(.headline);Text(detail(kind)).font(.caption).foregroundStyle(IRTheme.muted)};Spacer();Image(systemName:"chevron.right")}.padding(16).background(IRTheme.panel).clipShape(RoundedRectangle(cornerRadius:17))}.buttonStyle(.plain)}}.padding()}.background(IRTheme.background).foregroundStyle(.white).navigationTitle("Start Ride").toolbar{ToolbarItem(placement:.cancellationAction){Button("Cancel"){dismiss()}}}}}
    private func detail(_ kind:RideKind)->String{switch kind{case .solo:return "Training, touring or free ride";case .soloTimeTrial:return "Personal clock and course pacing";case .criterium:return "Lap racing and final sprint alerts";case .teamTimeTrial:return "Paceline gaps, pull time and rotations";case .teamRoadRace:return "GC, support, leadout and sprinter roles"}}
}

struct SensorSheet:View{
    @EnvironmentObject var bluetooth:BluetoothSensorManager;@Environment(\.dismiss) var dismiss
    var body:some View{NavigationStack{VStack(spacing:12){Text(bluetooth.bluetoothStatus).font(.caption.weight(.bold)).foregroundStyle(IRTheme.cyan);ScrollView{LazyVStack(spacing:9){if bluetooth.devices.isEmpty{ContentUnavailableView("No devices yet",systemImage:"antenna.radiowaves.left.and.right",description:Text("Press Scan and allow Bluetooth access."))}ForEach(bluetooth.devices){device in Button{bluetooth.toggle(device.id)}label:{HStack{Image(systemName:device.selected ? "checkmark.square.fill":"square").foregroundStyle(device.selected ? IRTheme.lime:IRTheme.muted);VStack(alignment:.leading){Text(device.name).font(.headline);Text("RSSI \(device.rssi) • \(device.connected ? "CONNECTED":"AVAILABLE")").font(.caption).foregroundStyle(device.connected ? IRTheme.lime:IRTheme.muted)};Spacer();if device.connected{Image(systemName:"link.circle.fill").foregroundStyle(IRTheme.cyan)}}.padding(14).background(IRTheme.panel).clipShape(RoundedRectangle(cornerRadius:15))}.buttonStyle(.plain)}}};HStack{Button(bluetooth.scanning ? "STOP SCAN":"SCAN"){bluetooth.scanning ? bluetooth.stopScan():bluetooth.startScan()}.buttonStyle(.bordered);Button("CONNECT CHECKED"){bluetooth.connectSelected()}.buttonStyle(.borderedProminent)}.padding(.bottom)}.padding(.horizontal).background(IRTheme.background).foregroundStyle(.white).navigationTitle("Sensors & Devices").toolbar{ToolbarItem(placement:.confirmationAction){Button("Done"){dismiss()}}}}}
}
